# For condition grammar see: https://docs.mergify.com/conditions/#grammar

shared:
  conditions:
    - and: &pr_ready_checks
      - "#approved-reviews-by>=1"  # A '#' pulls the length of the underlying list
      - "label=ready-to-merge"
      - "check-success=tests"

queue_rules:
  - name: default
    conditions:
      - and: *pr_ready_checks

pull_request_rules:
  - name: main branch PRs - Add to merge queue on approval
    conditions:
      - and: *pr_ready_checks
      - "base=main"  # Only branches that target main
      - "-head~=^develop"  # Don't include develop branches
    actions:
      queue:
        method: squash
        priority: medium

  - name: main branch PRs from develop branches - Add to merge queue on approval without squashing
    conditions:
      - and: *pr_ready_checks
      - "base=main"  # Only branches that target main
      - "-head~=^develop"  # Don't include develop branches
    actions:
      queue:
        method: rebase
        priority: high

  - name: develop branch PRs - Add to merge queue on approval
    conditions:
      - and: *pr_ready_checks
      - "base~=^develop"  # Filter branches by name
      - "-head~=^develop"  # Don't include develop branches
    actions:
      queue:
        method: squash
        priority: medium

  - name: Automatic PR branch updates
    conditions:
      - "queue-position=-1"  # Not queued
    actions:
      update:

  - name: Clean up after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
      label:
        remove:
          - "merge-conflicts"
          - "ready-to-merge"
          - "tests-failing"

  - name: Toggle label on merge conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - "merge-conflicts"

  # Don't use a toggle for this, as the label constantly gets applied and removed when tests are rerun.
  - name: Add label on test failures
    conditions:
      - or:
        - check-failure=tests
        - check-skipped=tests
    actions:
      label:
        add:
          - "tests-failing"

  - name: Remove label on test success
    conditions:
      - check-success=tests
    actions:
      label:
        remove:
          - "tests-failing"
