# Configuration file for Mega-Linter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
VALIDATE_ALL_CODEBASE: true
IGNORE_GITIGNORED_FILES: true
FILTER_REGEX_EXCLUDE: "(.*/?packages/.*)" # Ignore packages directories

ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - RST_RST_LINT
  - RST_RSTCHECK
  - RST_RSTFMT
  - YAML_PRETTIER
  - YAML_V8R
  - YAML_YAMLLINT

PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CLI_LINT_MODE: project
PYTHON_RUFF_FORMAT_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_FORMAT_CLI_LINT_MODE: project
