ignore:
  - "newreilc/hooks/component_sentry.py"
  - "newrelic/admin/*"
  - "newrelic/console.py"
  - "newrelic/hooks/adapter_flup.py"
  - "newrelic/hooks/adapter_meinheld.py"
  - "newrelic/hooks/adapter_paste.py"
  - "newrelic/hooks/component_piston.py"
  - "newrelic/hooks/database_oursql.py"
  - "newrelic/hooks/database_psycopg2ct.py"
  - "newrelic/hooks/datastore_aioredis.py"
  - "newrelic/hooks/datastore_aredis.py"
  - "newrelic/hooks/datastore_motor.py"
  - "newrelic/hooks/datastore_pyelasticsearch.py"
  - "newrelic/hooks/datastore_umemcache.py"
  - "newrelic/hooks/external_dropbox.py"
  - "newrelic/hooks/external_facepy.py"
  - "newrelic/hooks/external_pywapi.py"
  - "newrelic/hooks/external_xmlrpclib.py"
  - "newrelic/hooks/framework_pylons.py"
  - "newrelic/hooks/framework_web2py.py"
  - "newrelic/hooks/framework_webpy.py"
  - "newrelic/hooks/middleware_weberror.py"
  - "newrelic/packages/*"
  - "newrelic/packages/**/*"
