ignore:
  - "newrelic/packages/**/*"
  - "newrelic/packages/*"
  - "newrelic/hooks/adapter_meinheld.py"
  - "newrelic/hooks/adapter_flup.py"
  - "newrelic/hooks/component_piston.py"
  - "newrelic/hooks/datastore_pyelasticsearch.py"
  - "newrelic/hooks/external_pywapi.py"
  - "newrelic/hooks/external_dropbox.py"
  - "newrelic/hooks/external_facepy.py"
  - "newrelic/hooks/external_xmlrpclib.py"
  - "newrelic/hooks/framework_pylons.py"
  - "newrelic/hooks/framework_web2py.py"
  - "newrelic/hooks/middleware_weberror.py"
