# Copyright 2010 New Relic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This is a mapping of the entry_point name of the
# OpenTelemetry instrumentor and the list of targets in the
# NR hooks that need to be disabled if the OpenTelemetry
# instrumentor is to be used instead.
HYBRID_AGENT_DEFAULT_INCLUDED_TRACERS_TO_NR_HOOKS = {
    "aio-pika": [],
    "aiohttp_client": ["aiohttp.client", "aiohttp.client_reqrep"],
    "aiohttp_server": [
        "aiohttp.web",
        "aiohttp.wsgi",
        "aiohttp.web_reqrep",
        "aiohttp.web_response",
        "aiohttp.web_urldispatcher",
        "aiohttp.protocol",
    ],
    "aiokafka": [],
    "aiopg": [
        "psycopg2",
        "psycopg2._psycopg2",
        "psycopg2.extensions",
        "psycopg2._json",
        "psycopg2._range",
        "psycopg2.sql",
    ],
    "ariadne": [
        "ariadne.graphql",
        "graphql.graphql",
        "graphql.execution.execute",
        "graphql.execution.executor",
        "graphql.execution.middleware",
        "graphql.execution.utils",
        "graphql.error.located_error",
        "graphql.language.parser",
        "graphql.validation.validate",
        "graphql.validation.validation",
        "graphql.type.schema",
    ],
    "asyncclick": [],
    "asyncpg": ["asyncpg.connect_utils", "asyncpg.protocol"],
    # "boto": [], # this is boto3
    # "boto3": [],    # this is boto3sqs
    # "botocore": [],
    "cassandra": ["cassandra", "cassandra.cluster"],
    "celery": ["celery.local", "celery.app.trace", "celery.worker", "celery.concurrency.prefork", "billiard.pool"],
    "click": [],
    "confluent_kafka": [
        "confluent_kafka.cimpl",
        "confluent_kafka.serializing_producer",
        "confluent_kafka.deserializing_consumer",
    ],
    "django": [
        "django.core.handlers.base",
        "django.core.handlers.asgi",
        "django.core.handlers.wsgi",
        "django.core.urlresolvers",
        "django.template",
        "django.template.loader_tags",
        "django.core.servers.basehttp",
        "django.contrib.staticfiles.views",
        "django.contrib.staticfiles.handlers",
        "django.views.debug",
        "django.http.multipartparser",
        "django.core.mail",
        "django.core.mail.message",
        "django.views.generic.base",
        "django.core.management.base",
        "django.template.base",
        "django.middleware.gzip",
        "django.urls.resolvers",
        "django.urls.base",
        "django.core.handlers.exception",
    ],
    "elasticsearch": [
        "elasticsearch.client",
        "elasticsearch._async.client",
        "elasticsearch._sync.client",
        "elasticsearch._async.client",
        "elasticsearch.client.cat",
        "elasticsearch._async.client.cat",
        "elasticsearch._sync.client.cat",
        "elasticsearch.client.cluster",
        "elasticsearch._async.client.cluster",
        "elasticsearch._sync.client.cluster",
        "elasticsearch.client.indices",
        "elasticsearch._async.client.indices",
        "elasticsearch._sync.client.indices",
        "elasticsearch.client.nodes",
        "elasticsearch._async.client.nodes",
        "elasticsearch._sync.client.nodes",
        "elasticsearch.client.snapshot",
        "elasticsearch._async.client.snapshot",
        "elasticsearch._sync.client.snapshot",
        "elasticsearch.client.tasks",
        "elasticsearch._async.client.tasks",
        "elasticsearch._sync.client.tasks",
        "elasticsearch.client.ingest",
        "elasticsearch._async.client.ingest",
        "elasticsearch._sync.client.ingest",
        "elasticsearch.connection.base",
        "elasticsearch._async.http_aiohttp",
        "elastic_transport._node._base",
        "elastic_transport._node._base_async",
        "elasticsearch.transport",
        "elasticsearch._async.transport",
        "elastic_transport._transport",
        "elastic_transport._async_transport",
    ],
    "falcon": ["falcon.api", "falcon.app", "falcon.routing.util"],
    "fastapi": [
        "fastapi.routing",
        "starlette.requests",
        "starlette.routing",
        "starlette.applications",
        "starlette.middleware.errors",
        "starlette.middleware.exceptions",
        "starlette.exceptions",
        "starlette.background",
    ],
    "flask": ["flask.app", "flask.templating", "flask.blueprints", "flask.views"],
    "httpx": ["httpx._client", "urllib.request"],
    "jinja2": ["jinja2.environment"],
    "kafka": ["kafka.consumer.group", "kafka.producer.kafka", "kafka.coordinator.heartbeat"],
    "logging": ["logging"],
    "mysql": ["mysql.connector"],
    "mysqlclient": ["MySQLdb"],
    "pika": ["pika.adapters", "pika.channel", "pika.spec"],
    "psycopg": ["psycopg", "psycopg.sql"],
    "psycopg2": [
        "psycopg2",
        "psycopg2._psycopg2",
        "psycopg2.extensions",
        "psycopg2._json",
        "psycopg2._range",
        "psycopg2.sql",
    ],
    "pymemcache": ["pymemcache.client"],
    "pymongo": [
        "pymongo.synchronous.pool",
        "pymongo.asynchronous.pool",
        "pymongo.synchronous.collection",
        "pymongo.asynchronous.collection",
        "pymongo.synchronous.mongo_client",
        "pymongo.asynchronous.mongo_client",
        "pymongo.connection",
        "pymongo.collection",
        "pymongo.mongo_client",
    ],
    "pymssql": ["pymssql"],
    "pymysql": ["pymysql"],
    "pyramid": ["pyramid.router", "pyramid.config", "pyramid.config.views", "pyramid.config.tweens"],
    "redis": [
        "redis.asyncio.client",
        "redis.asyncio.commands",
        "redis.asyncio.connection",
        "redis.connection",
        "redis.client",
        "redis.commands.cluster",
        "redis.commands.core",
        "redis.commands.sentinel",
        "redis.commands.json.commands",
        "redis.commands.search.commands",
        "redis.commands.timeseries.commands",
        "redis.commands.bf.commands",
        "redis.commands.graph.commands",
        "redis.commands.vectorset.commands",
    ],
    "remoulade": [],
    "requests": [
        "requests.sessions",
        "requests.api",
        "urllib3.connectionpool",
        "urllib3.connection",
        "requests.packages.urllib3.connection",
        "http.client",
        "httplib2",
    ],
    "sqlalchemy": [],
    "sqlite3": ["sqlite3", "sqlite3.dbapi2", "pysqlite2", "pysqlite2.dbapi2"],
    "starlette": [
        "starlette.requests",
        "starlette.routing",
        "starlette.applications",
        "starlette.middleware.errors",
        "starlette.middleware.exceptions",
        "starlette.exceptions",
        "starlette.background",
        # "starlette.concurrency",  # This is deliberately excluded
    ],
    "strawberry-graphql": [
        "strawberry.schema.schema",
        "strawberry.schema.schema_converter",
        "graphql.graphql",
        "graphql.execution.execute",
        "graphql.execution.executor",
        "graphql.execution.middleware",
        "graphql.execution.utils",
        "graphql.error.located_error",
        "graphql.language.parser",
        "graphql.validation.validate",
        "graphql.validation.validation",
        "graphql.type.schema",
    ],
    "system_metrics": [],
    "threading": [],
    "tornado": [
        "tornado.httpserver",
        "tornado.httputil",
        "tornado.httpclient",
        "tornado.routing",
        "tornado.web",
        "http.client",
    ],
    "tortoiseorm": [],
    "urllib": ["urllib.request", "http.client"],
    "urllib3": ["urllib3.connectionpool", "urllib3.connection", "requests.packages.urllib3.connection", "http.client"],
}
