#!/usr/bin/env python3
# Copyright 2010 New Relic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Fleet Control Config Schema Generator -- Python Agent

This script was initially generated by Claude.

Reads newrelic.ini from the working tree and writes JSON Schema Draft
2020-12 to .fleetControl/schemas/config.json.

Source resolution:
  1. NEWRELIC_INI env var, if set
  2. <repo-root>/newrelic/newrelic.ini
     (resolved relative to this script's location)

Merge behavior:
  The generator never starts fresh -- each run deep-merges the freshly
  generated schema into whatever already exists at config.json. Properties
  are union'd (keys present only in the old schema are preserved); leaf
  nodes and the top-level `required` list take the new run's values. This
  guarantees the published schema only ever grows, so a config that
  validated against an older agent's schema continues to validate against
  the current one.

Exit codes:
  0 -- no schema changes (or first run)
  1 -- schema changed (CI should commit the updated files)
  2 -- hard failure (invalid schema, missing input, malformed
       configurationDefinitions.yml)

Run standalone:
  python generate-schema.py

Override the source file:
  NEWRELIC_INI=/path/to/newrelic.ini python generate-schema.py

---------------------------------------------------------------------------
Why the schema emits `additionalProperties: true`
---------------------------------------------------------------------------
The generator sets `additionalProperties: true` at the root. This is
intentional and serves two purposes:

  1. Forward compatibility. The agent ships new config keys in every
     release. A Fleet Control deployment may be validating against a
     schema generated from an older newrelic.ini -- strict validation
     would reject any newer key, breaking users who upgrade the agent
     before the schema is republished.

  2. Coverage gaps. Some keys are deliberately excluded (see EXCLUDE_KEYS)
     and some shapes the generator can't represent faithfully. Permitting
     unknown properties means a config that uses those still validates
     instead of being flagged as malformed.

If a future requirement calls for strict validation (catch typos, reject
unknown keys), flip this to `false` -- but doing so should be paired with
a release process that republishes the schema in lockstep with the agent.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths -- all resolved relative to this script. Script lives at
# <repo-root>/.fleetControl/schemaGeneration/ so the repo root is two
# levels up.
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
FLEET_CONTROL_DIR = SCRIPT_DIR.parent
REPO_ROOT = FLEET_CONTROL_DIR.parent
SCHEMA_DIR = FLEET_CONTROL_DIR / "schemas"
SCHEMA_PATH = SCHEMA_DIR / "config.json"
CONFIG_DEF_PATH = FLEET_CONTROL_DIR / "configurationDefinitions.yml"
DEFAULT_INI_PATH = REPO_ROOT / "newrelic" / "newrelic.ini"

# ---------------------------------------------------------------------------
# Enum / special-value overrides. Keys are dotted INI keys exactly as they
# appear in the schema's `properties` map.
# ---------------------------------------------------------------------------
ENUM_OVERRIDES = {
    "log_level": ["critical", "error", "warning", "info", "debug"],
    "transaction_tracer.record_sql": ["off", "raw", "obfuscated"],
}

# ---------------------------------------------------------------------------
# Type overrides -- when the INI default doesn't reflect the documented
# semantic. INI values are always strings, so settings that are really
# lists (space- or comma-separated) need explicit array typing.
# ---------------------------------------------------------------------------
TYPE_OVERRIDES = {
    "error_collector.ignore_classes":   {"type": "array", "items": {"type": "string"}, "default": []},
    "error_collector.expected_classes": {"type": "array", "items": {"type": "string"}, "default": []},
    "transaction_tracer.function_trace":{"type": "array", "items": {"type": "string"}, "default": []},
    "attributes.include":               {"type": "array", "items": {"type": "string"}, "default": []},
    "attributes.exclude":               {"type": "array", "items": {"type": "string"}, "default": []},
}

# ---------------------------------------------------------------------------
# Keys to exclude from the generated schema.
#
# Use this for settings the Fleet Control UI shouldn't surface -- typically
# because they are derived at runtime, structurally awkward to represent in
# JSON Schema, or only relevant for internal/debug scenarios.
#
# Add a key's exact dotted form (matching the property name in the schema).
# ---------------------------------------------------------------------------
EXCLUDE_KEYS = set()


# ---------------------------------------------------------------------------
# Type inference -- INI values are always strings; we infer the intended
# JSON Schema type from the string content.
# ---------------------------------------------------------------------------

_INT_RE = re.compile(r"^-?\d+$")
_FLOAT_RE = re.compile(r"^-?\d+\.\d+$")


def infer_type(value):
    """Infer a JSON Schema type from a raw INI string value.

    Returns one of: 'boolean', 'integer', 'number', 'string'. Empty strings
    return 'string' so the caller can decide whether to omit the default.
    """
    if value is None:
        return "string"
    s = value.strip()
    if s.lower() in ("true", "false"):
        return "boolean"
    if _INT_RE.match(s):
        return "integer"
    if _FLOAT_RE.match(s):
        return "number"
    return "string"


def coerce_default(value, json_type):
    """Convert a raw INI string to a Python value matching `json_type`."""
    s = value.strip()
    if json_type == "boolean":
        return s.lower() == "true"
    if json_type == "integer":
        return int(s)
    if json_type == "number":
        return float(s)
    return value  # preserve original string formatting


def make_property(key, raw_value, description, enum_overrides, type_overrides):
    """Build a JSON Schema property node for a single INI key.

    `raw_value` may be None (key was commented-out) or a string. Descriptions
    are trimmed; empty descriptions are omitted.
    """
    if key in type_overrides:
        prop = dict(type_overrides[key])
    elif key in enum_overrides:
        enum_vals = enum_overrides[key]
        prop = {"type": "string", "enum": list(enum_vals)}
        if raw_value is not None and raw_value.strip() in enum_vals:
            prop["default"] = raw_value.strip()
    else:
        json_type = infer_type(raw_value)
        prop = {"type": json_type}
        if raw_value is not None and raw_value != "":
            prop["default"] = coerce_default(raw_value, json_type)

    if description:
        prop["description"] = description.strip()
    return prop


# ---------------------------------------------------------------------------
# INI parsing -- pulls keys, raw values, and contiguous comment blocks
# attached to each key. Only the [newrelic] section is processed.
#
# We scan line-by-line rather than using configparser because:
#   1. configparser strips comments, so we'd lose the descriptions.
#   2. INI keys in this file include literal dots ('transaction_tracer.enabled'),
#      which configparser handles fine -- but we still need the comment scan.
#   3. We need to honor commented-out keys (e.g. '# proxy_host = hostname')
#      as descriptions for the *next* live key, NOT bleed onto it. A blank
#      line between resets the pending block; configparser would just skip.
# ---------------------------------------------------------------------------

# Section header: [newrelic] or [newrelic:production], etc.
_SECTION_RE = re.compile(r"^\s*\[([^\]]+)\]\s*$")
# Live key=value line. Keys may contain dots and underscores.
_KEY_RE = re.compile(r"^([a-zA-Z_][\w.\-]*)\s*=\s*(.*)$")


def parse_ini(text, section="newrelic"):
    """Parse `text` and return (keys, comments) for the named section.

    `keys` is an OrderedDict-style {key: raw_value_string_or_None} preserving
    insertion order. `comments` is {key: joined_comment_string}. Only commented-
    out keys whose name matches another live key are dropped (they served as
    description anchors); the rest are ignored.

    A blank line clears any pending comment block, so commented-out config
    examples do not bleed into the next live key's description.
    """
    keys = {}
    comments = {}
    pending = []
    current_section = None

    for raw_line in text.splitlines():
        line = raw_line.rstrip("\r")
        stripped = line.strip()

        if stripped == "":
            pending = []
            continue

        m = _SECTION_RE.match(line)
        if m:
            current_section = m.group(1).strip()
            pending = []
            continue

        if line.lstrip().startswith("#"):
            # Strip leading '#' and one optional space. Preserve the rest.
            content = line.lstrip()[1:]
            if content.startswith(" "):
                content = content[1:]
            pending.append(content.rstrip())
            continue

        if current_section != section:
            pending = []
            continue

        km = _KEY_RE.match(line)
        if km:
            key = km.group(1)
            value = km.group(2).strip()
            keys[key] = value
            if pending:
                comments[key] = " ".join(p.strip() for p in pending if p.strip())
            pending = []
        else:
            pending = []

    return keys, comments


# ---------------------------------------------------------------------------
# Schema generation
# ---------------------------------------------------------------------------

LICENSE_KEY_OVERRIDE = {
    "type": "string",
    "description": (
        "New Relic license key associated with your account. "
        "Binds the agent's data to your account in the New Relic UI."
    ),
    "minLength": 1,
}


def build_properties(keys, comments, exclude_keys, enum_overrides, type_overrides):
    """Build the JSON Schema `properties` map from parsed INI keys."""
    properties = {}
    for key, raw_value in keys.items():
        if key in exclude_keys:
            continue
        desc = comments.get(key, "")
        properties[key] = make_property(
            key, raw_value, desc, enum_overrides, type_overrides
        )
    return properties


def generate_schema(ini_text, exclude_keys=None, enum_overrides=None, type_overrides=None):
    """Generate a JSON Schema dict from raw newrelic.ini text."""
    if exclude_keys is None:
        exclude_keys = EXCLUDE_KEYS
    if enum_overrides is None:
        enum_overrides = ENUM_OVERRIDES
    if type_overrides is None:
        type_overrides = TYPE_OVERRIDES

    keys, comments = parse_ini(ini_text, section="newrelic")
    properties = build_properties(
        keys, comments, exclude_keys, enum_overrides, type_overrides
    )

    if "license_key" in properties:
        properties["license_key"] = dict(LICENSE_KEY_OVERRIDE)

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "New Relic Python Agent Configuration",
        "description": (
            "Fleet Control configuration schema for the New Relic Python agent. "
            "Generated from newrelic/newrelic.ini."
        ),
        "type": "object",
        "properties": properties,
        "required": ["license_key", "app_name"],
        "additionalProperties": True,
    }


# ---------------------------------------------------------------------------
# Schema merge -- deep-merges a freshly generated schema into the existing
# one so the published schema only ever grows. Behavior:
#
#   * `properties` maps are union'd by key. Keys only in the old schema are
#     preserved verbatim; keys only in the new schema are added; keys in both
#     recurse if both sides are object nodes, otherwise the new leaf wins.
#   * Top-level scalars and arrays (`title`, `description`, `required`,
#     `additionalProperties`, etc.) take the new run's value.
#
# Why old leaves don't survive a type change: if a key in newrelic.ini moves
# from `enabled = true` to `count = 5`, the schema must reflect the current
# shape so validation matches reality. Only the *key* is preserved across
# runs, not the constraint that no longer applies.
# ---------------------------------------------------------------------------

def merge_schemas(old_s, new_s):
    if not old_s:
        return new_s

    merged = dict(new_s)

    old_props = old_s.get("properties") or {}
    new_props = new_s.get("properties") or {}
    if old_props or new_props:
        merged["properties"] = merge_properties(old_props, new_props)

    return merged


def merge_properties(old_props, new_props):
    result = {}
    # Walk new first so keys in both retain new ordering.
    for key, new_val in new_props.items():
        if (
            key in old_props
            and isinstance(new_val, dict)
            and isinstance(old_props[key], dict)
            and new_val.get("type") == "object"
            and old_props[key].get("type") == "object"
        ):
            result[key] = merge_schemas(old_props[key], new_val)
        else:
            result[key] = new_val
    # Carry forward keys only in old.
    for key, old_val in old_props.items():
        if key not in result:
            result[key] = old_val
    return result


# ---------------------------------------------------------------------------
# Schema diff classification -- distinguishes breaking from additive changes.
# Change records are plain dicts:
#   {path: str, kind: str, severity: 'breaking'|'additive'|'cosmetic',
#    detail: str}
# ---------------------------------------------------------------------------

def render_change(c):
    kind = c["kind"]
    sym = "+" if kind == "added" else ("-" if kind == "removed" else "~")
    detail = c.get("detail") or ""
    path = c["path"]
    return f"{sym} {path}: {detail}" if detail else f"{sym} {path}"


def classify_changes(old_s, new_s, path=""):
    changes = []

    old_req = set(old_s.get("required") or [])
    new_req = set(new_s.get("required") or [])
    for k in sorted(new_req - old_req):
        changes.append({
            "path": f"{path}.{k}" if path else k,
            "kind": "required_added",
            "severity": "breaking",
            "detail": "now required",
        })
    for k in sorted(old_req - new_req):
        changes.append({
            "path": f"{path}.{k}" if path else k,
            "kind": "required_removed",
            "severity": "additive",
            "detail": "no longer required",
        })

    old_ap = old_s.get("additionalProperties", True)
    new_ap = new_s.get("additionalProperties", True)
    if old_ap is True and new_ap is False:
        changes.append({
            "path": path or "<root>",
            "kind": "additional_properties_tightened",
            "severity": "breaking",
            "detail": "additionalProperties: true -> false",
        })
    elif old_ap is False and new_ap is True:
        changes.append({
            "path": path or "<root>",
            "kind": "additional_properties_loosened",
            "severity": "additive",
            "detail": "additionalProperties: false -> true",
        })

    old_props = old_s.get("properties") or {}
    new_props = new_s.get("properties") or {}
    for key in sorted(set(old_props.keys()) | set(new_props.keys())):
        child_path = f"{path}.{key}" if path else key
        if key not in old_props:
            changes.append({
                "path": child_path, "kind": "added",
                "severity": "additive", "detail": "new property",
            })
        elif key not in new_props:
            changes.append({
                "path": child_path, "kind": "removed",
                "severity": "breaking", "detail": "property removed",
            })
        else:
            op = old_props[key]
            np = new_props[key]
            if op.get("type") == "object" and np.get("type") == "object":
                changes.extend(classify_changes(op, np, child_path))
            else:
                changes.extend(classify_leaf(op, np, child_path))
    return changes


def classify_leaf(op, np, path):
    changes = []

    if op.get("type") != np.get("type"):
        changes.append({
            "path": path, "kind": "type_changed", "severity": "breaking",
            "detail": f"type {op.get('type')} -> {np.get('type')}",
        })

    oe = op.get("enum")
    ne = np.get("enum")
    if oe is None and ne is not None:
        changes.append({
            "path": path, "kind": "enum_introduced", "severity": "breaking",
            "detail": f"newly constrained to enum {ne}",
        })
    elif oe is not None and ne is None:
        changes.append({
            "path": path, "kind": "enum_removed_entirely", "severity": "additive",
            "detail": "enum constraint removed",
        })
    elif oe and ne and set(oe) != set(ne):
        for v in sorted(set(oe) - set(ne)):
            changes.append({
                "path": path, "kind": "enum_value_removed", "severity": "breaking",
                "detail": f"enum value '{v}' removed",
            })
        for v in sorted(set(ne) - set(oe)):
            changes.append({
                "path": path, "kind": "enum_value_added", "severity": "additive",
                "detail": f"enum value '{v}' added",
            })

    if op.get("default") != np.get("default"):
        changes.append({
            "path": path, "kind": "default_changed", "severity": "additive",
            "detail": f"default {op.get('default')} -> {np.get('default')}",
        })

    if op.get("description") != np.get("description"):
        changes.append({
            "path": path, "kind": "description_changed", "severity": "cosmetic",
            "detail": "description updated",
        })

    return changes


# ---------------------------------------------------------------------------
# Semver bump
# ---------------------------------------------------------------------------

def recommend_bump(changes):
    if any(c.get("severity") == "breaking" for c in changes):
        return "major"
    if any(c.get("severity") == "additive" for c in changes):
        return "minor"
    if any(c.get("severity") == "cosmetic" for c in changes):
        return "patch"
    return "none"


def apply_bump(version, bump):
    if bump == "none":
        return version
    parts = version.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise ValueError(f"version '{version}' is not semver MAJOR.MINOR.PATCH")
    major, minor, patch = (int(p) for p in parts)
    if bump == "major":
        return f"{major + 1}.0.0"
    if bump == "minor":
        return f"{major}.{minor + 1}.0"
    if bump == "patch":
        return f"{major}.{minor}.{patch + 1}"
    raise ValueError(f"unknown bump kind '{bump}'")


# Match a `version: X` line, capturing leading whitespace for round-trip.
_VERSION_LINE_RE = re.compile(r"(?m)^(\s*version:\s*)(\S+)(\s*)$")


def bump_version(yaml_path, bump, write):
    """Read configurationDefinitions.yml, compute new version, optionally
    write it back. Returns (old_version, new_version).

    Reading is a regex match (no PyYAML dep). Writing replaces only the
    single `version:` line so the rest of the file is preserved byte-for-byte.
    """
    text = Path(yaml_path).read_text(encoding="utf-8")
    matches = list(_VERSION_LINE_RE.finditer(text))
    if len(matches) != 1:
        raise RuntimeError(
            f"{yaml_path}: expected exactly 1 'version:' line, found {len(matches)}"
        )
    old_version = matches[0].group(2)
    new_version = apply_bump(old_version, bump)
    if write and new_version != old_version:
        new_text = _VERSION_LINE_RE.sub(
            lambda m: f"{m.group(1)}{new_version}{m.group(3)}",
            text,
        )
        Path(yaml_path).write_text(new_text, encoding="utf-8")
    return old_version, new_version


# ---------------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------------

def load_newrelic_ini(default_path):
    env_path = os.environ.get("NEWRELIC_INI")
    source = Path(env_path) if env_path else Path(default_path)
    if not source.exists():
        raise FileNotFoundError(
            f"newrelic.ini not found at {source.resolve()}. "
            "Set NEWRELIC_INI to override the source path."
        )
    print(f"Reading: {source.resolve()}")
    return source.read_text(encoding="utf-8")


def load_existing(path):
    if not Path(path).exists():
        return {}
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def write_schema(schema, path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")


def validate_meta_schema(schema):
    """Validate against JSON Schema 2020-12. Soft-skip if `jsonschema` is not
    installed; hard-fail (exit 2) only on actual schema invalidity.
    """
    try:
        import jsonschema  # type: ignore
    except ImportError:
        print("  meta-schema check skipped: jsonschema not installed", file=sys.stderr)
        return
    try:
        jsonschema.Draft202012Validator.check_schema(schema)
        print("Meta-schema validation passed (Draft 2020-12)")
    except jsonschema.exceptions.SchemaError as e:
        print("Meta-schema validation FAILED:", file=sys.stderr)
        print(f"  {e.message}", file=sys.stderr)
        sys.exit(2)
    except Exception as e:  # noqa: BLE001
        print(f"  meta-schema check skipped: {type(e).__name__}: {e}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate Fleet Control config schema.")
    parser.add_argument("--ci", action="store_true",
                        help="Apply the recommended (or overridden) version bump in place.")
    parser.add_argument("--bump", choices=["major", "minor", "patch", "none"],
                        help="Override the auto-recommended bump.")
    args = parser.parse_args(argv)

    raw_text = load_newrelic_ini(DEFAULT_INI_PATH)
    generated = generate_schema(raw_text)

    old_schema = load_existing(SCHEMA_PATH)
    new_schema = merge_schemas(old_schema, generated)

    validate_meta_schema(new_schema)

    write_schema(new_schema, SCHEMA_PATH)
    print(f"Wrote:   {SCHEMA_PATH}")

    if not old_schema:
        print("\nFirst run -- schema created.")
        return 0

    changes = classify_changes(old_schema, new_schema)

    if changes:
        breaking = [c for c in changes if c["severity"] == "breaking"]
        additive = [c for c in changes if c["severity"] == "additive"]
        cosmetic = [c for c in changes if c["severity"] == "cosmetic"]
        print(f"\nSchema changes ({len(changes)}):")
        if breaking:
            print(f"  BREAKING ({len(breaking)}):")
            for c in breaking:
                print(f"    {render_change(c)}")
        if additive:
            print(f"  ADDITIVE ({len(additive)}):")
            for c in additive:
                print(f"    {render_change(c)}")
        if cosmetic:
            print(f"  COSMETIC ({len(cosmetic)}):")
            for c in cosmetic:
                print(f"    {render_change(c)}")
    else:
        print("\nNo schema changes.")

    auto_bump = recommend_bump(changes)
    chosen = args.bump or auto_bump
    old_v, new_v = bump_version(CONFIG_DEF_PATH, chosen, args.ci)
    if chosen == "none" or new_v == old_v:
        print(f"\nRecommended bump: none ({old_v} unchanged)")
    elif args.bump and args.bump != auto_bump:
        print(f"\nRecommended bump: {auto_bump} -> overridden to {chosen} ({old_v} -> {new_v})")
    else:
        print(f"\nRecommended bump: {chosen} ({old_v} -> {new_v})")
    if args.ci and new_v != old_v:
        print(f"Wrote:   {CONFIG_DEF_PATH}")

    return 1 if changes else 0


if __name__ == "__main__":
    sys.exit(main())
