name: "setup-python-matrix"
description: "Sets up all versions of python required for matrix testing in this repo."
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "pypy-3.7"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "pypy-2.7"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        architecture: x64

    - uses: actions/setup-python@v4
      with:
        python-version: "2.7"
        architecture: x64

    - name: Install Dependencies
      shell: bash
      run: |
        python3.10 -m pip install -U pip
        python3.10 -m pip install -U wheel setuptools 'tox<4' virtualenv!=20.0.24
