version: '3'

services: 
  app:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:437.0.1-emulators
    command: ["gcloud", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]
    ports:
      - 8080:8080
      - 8081:8080
