# -*- coding: utf-8 -*-
# =============================================================================
# WARNING: Generated from proto files edited with the following changes.
# 1. Replace listed .proto file paths with newrelic/packages/opentelemetry_proto/
# 2. Replace listed __module__ paths with newrelic.packages.opentelemetry_proto
# This prevents conflicts with other packages using different versions
# of opentelemetry's pb2 files.
# =============================================================================
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newrelic/packages/opentelemetry_proto/resource.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from newrelic.packages.opentelemetry_proto import common_pb2 as newrelic_dot_packages_dot_opentelemetry__proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4newrelic/packages/opentelemetry_proto/resource.proto\x12%newrelic.packages.opentelemetry_proto\x1a\x32newrelic/packages/opentelemetry_proto/common.proto\"q\n\x08Resource\x12\x43\n\nattributes\x18\x01 \x03(\x0b\x32/.newrelic.packages.opentelemetry_proto.KeyValue\x12 \n\x18\x64ropped_attributes_count\x18\x02 \x01(\rB\x83\x01\n\"io.opentelemetry.proto.resource.v1B\rResourceProtoP\x01Z*go.opentelemetry.io/proto/otlp/resource/v1\xaa\x02\x1fOpenTelemetry.Proto.Resource.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'newrelic.packages.opentelemetry_proto.resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"io.opentelemetry.proto.resource.v1B\rResourceProtoP\001Z*go.opentelemetry.io/proto/otlp/resource/v1\252\002\037OpenTelemetry.Proto.Resource.V1'
  _globals['_RESOURCE']._serialized_start=147
  _globals['_RESOURCE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
